### ISSUE TITLE
add supported i18n libraries to fink product page

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-fink#22]
@samuel.stroschein said in [SHERL-47](https://linear.app/opral/issue/SHERL-47/add-supported-i18n-libraries-to-product-page#comment-d31fba5a):

> this will be helpful for fink too, see [https://discord.com/channels/897438559458430986/1084866774874468433/1242165023779061881](https://discord.com/channels/897438559458430986/1084866774874468433/1242165023779061881)

**Comment by NiklasBuchfink** [comment]
I will add a table to the "Get started". This makes it easy to find out whether the i18n library is supported and which plugin to use.

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/b620c567-3365-4777-b76a-e4a46a7afbd2/44b2c174-e3f3-42da-8f61-d29f46b2993b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9iNjIwYzU2Ny0zMzY1LTQ3NzctYjc2YS1lNGE0NmE3YWZiZDIvNDRiMmMxNzQtZTNmMy00MmRhLThmNjEtZDI5ZjQ2YjI5OTNiIiwiaWF0IjoxNzE2MzI5OTA4LCJleHAiOjMzMjg2ODg5OTA4fQ.d7O82mb_oP00xDhSDvKqSH6jYUypRCOWR6fK-1dU5K8 " alt="image.png" width="2702" height="1469" />

**Comment by NiklasBuchfink** [comment]
Related commit: [https://github.com/opral/monorepo/commit/989df304b69fc8cec736dcc862922481b3e355d7](https://github.com/opral/monorepo/commit/989df304b69fc8cec736dcc862922481b3e355d7)

**Comment by samuelstroschein** [comment]
btw does `createNewProject()` already exists? If so, you can remove the create a folder and file stuff from the getting started. Actually, i don't think you need docs for getting started at all anymore.

Regardless, I recommend a supported i18n libraries page because ppl adopting fink are asking "does this work with i18next" etc

**Comment by NiklasBuchfink** [comment]
It exists, it's just not implemented yet. The best would be to select the library import or export within Fink.<br><br>I have the same feeling. It is such a simple app and the UI should be self-explanatory, including a getting started section.

> Regardless, I recommend a supported i18n libraries page because ppl adopting fink are asking "does this work with i18next" etc

I make a section with the logos of Paraglide JS, i18next and next-intl and add the disclaimer "and other JSON-based i18n libraries".

**Comment by NiklasBuchfink** [comment]
<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/629bdc09-8c11-4fef-a326-b6756a13040e/1b8c9b5b-3b32-4499-8353-f3532bc7d536?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC82MjliZGMwOS04YzExLTRmZWYtYTMyNi1iNjc1NmExMzA0MGUvMWI4YzliNWItM2IzMi00NDk5LTgzNTMtZjM1MzJiYzdkNTM2IiwiaWF0IjoxNzE2Mzg0NjY2LCJleHAiOjMzMjg2OTQ0NjY2fQ.3IBz40XIDKl_jabouRTBHqFnO4YIDdwXTHfwAafU3yg " alt="image.png" width="1647" height="638" />

Section is online ✅<br>Would have been great to center the text below, but it doesn't work with the feature section nor pure HTML. I think it works for now.

**Comment by samuelstroschein** [comment]
@niklas.buchfink i would link to the plugins. else you get the question "how can i make fink work with i18next?"

**Comment by NiklasBuchfink** [comment]
I added two more sentences that link to the plugins and the getting started with the table

**Comment by samuelstroschein** [comment]
@niklas.buchfink i couldn't find which plugins your support because i wouldn't search in "getting started" to find *before i get started* if a plugin exits. 

i propose to add a new section "supported i18n libraries" and just link to the plugins 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/dc74408a-2a38-47b7-85ce-7e408dc5701b/1c67a238-1461-4c86-b5eb-55b4022a3697?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9kYzc0NDA4YS0yYTM4LTQ3YjctODVjZS03ZTQwOGRjNTcwMWIvMWM2N2EyMzgtMTQ2MS00Yzg2LWI1ZWItNTViNDAyMmEzNjk3IiwiaWF0IjoxNzE2Mzk2MTQ1LCJleHAiOjMzMjg2OTU2MTQ1fQ.d-0H-l6_zdx2gJ3uO0GiRCAWBj4r52EbeqINwD6fTPc " alt="CleanShot 2024-05-22 at 12.41.52@2x.png" width="1652" height="1586" />

**Comment by samuelstroschein** [comment]
i also recommend to remove the getting started. there is no valuable information in there: 

*  nobody will manually create a project.inlang folder
* plugins should be listed outisde the getting started
* optionally installing lint rules can be done directly in app
* example obsolet.

**Comment by NiklasBuchfink** [comment]
Just out of interest, did you write that before the sentences below were live? The website deployment only runs if something changes in the website folder, so maybe it wasn't live.

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/cfd41063-aef8-4914-8c65-262b6a752506/7a7e35ba-9d08-4487-8fae-67e86c7db317?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9jZmQ0MTA2My1hZWY4LTQ5MTQtOGM2NS0yNjJiNmE3NTI1MDYvN2E3ZTM1YmEtOWQwOC00NDg3LThmYWUtNjdlODZjN2RiMzE3IiwiaWF0IjoxNzE2NDEwNDUwLCJleHAiOjMzMjg2OTcwNDUwfQ.0UV1V17GkVHU_sGqkKBZ4kUiFxMVJ8do5uQ4F6NCbtI " alt="image.png" width="1551" height="703" />

<br>Anyway, I agree that the product page of Fink needs to check all the boxes like library compatibility. <br><br>The onboarding should be done in app:

1. getting started by createProject
2. select import/export (plugins)
3. install lint rules

How would you install lint rules in-app?<br>The settings component can't do it yet and apps can't list the available lint rules without opening inlang.com.

**Comment by samuelstroschein** [comment]
> How would you install lint rules in-app?
> The settings component can't do it yet and apps can't list the available lint rules without opening inlang.com.

Either via the settings component, or a new shared `<inlang-module-management>` component
