### ISSUE TITLE
public repo can't be opened

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-fink#23]
### Context

The public repo [https://fink.inlang.com/github.com/spuithori/tokimekibluesky](https://fink.inlang.com/github.com/spuithori/tokimekibluesky) can't be opened without being signed in

[https://www.loom.com/share/97f1aad71f6e407da95d98f9585a3b01?sid=85bebf68-7b8d-4b7d-9f3c-d98226697d7c](https://www.loom.com/share/97f1aad71f6e407da95d98f9585a3b01?sid=85bebf68-7b8d-4b7d-9f3c-d98226697d7c)

## reproduction

open [https://fink.inlang.com/github.com/spuithori/tokimekibluesky](https://fink.inlang.com/github.com/spuithori/tokimekibluesky)

**Comment by samuelstroschein** [comment]
those github related problems are really bothering me

**Comment by NiklasBuchfink** [comment]
Felix had the same issue here [FINK-33](https://linear.app/opral/issue/FINK-33/issues-and-observations-in-fink-while-working-on-branch-feature) <br><br>I can't reproduce it in Edge, Chrome or Firefox

**Comment by samuelstroschein** [comment]
@niklas.buchfink i can't reproduce either anymore. closing as can't repro
