### ISSUE TITLE
the doc won't let me push changes

### ISSUE THREAD

**Issue by goksugkdd** [opral/inlang-fink#24]
![image](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/09b1b163-e085-45d4-9688-5ebcb2a14d4d/5778ff5e-a804-425e-956e-8341a90c46c8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wOWIxYjE2My1lMDg1LTQ1ZDQtOTY4OC01ZWJjYjJhMTRkNGQvNTc3OGZmNWUtYTgwNC00MjVlLTk1NmUtODM0MWE5MGM0NmM4IiwiaWF0IjoxNzE2NTU3ODY1LCJleHAiOjMzMjg3MTE3ODY1fQ.77DEsRu2wW9YkIKXbNMLm_TCQt6GBXc2gg2rwGlb7hQ)

this is the errror code i get when i try to save the changes in the document.

this is the line

![image](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/00213958-9d9d-427e-aaae-57c4a8f29791/17948a19-ae7c-45fc-bfa3-ecf5f74b8df3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wMDIxMzk1OC05ZDlkLTQyN2UtYWFhZS01N2M0YThmMjk3OTEvMTc5NDhhMTktYWU3Yy00NWZjLWJmYTMtZWNmNWY3NGI4ZGYzIiwiaWF0IjoxNzE2NTU3ODY1LCJleHAiOjMzMjg3MTE3ODY1fQ.yr9nxyWUMml8caqvVOIK7enKOJ8CtBogx9a7S0NZLDU)

and this is the change i am trying to save

![image](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/ac07a518-4bd4-49dc-b0ef-6b9eaafedeb1/5ec14448-2e9d-414e-bddb-c5a76dd6bd72?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9hYzA3YTUxOC00YmQ0LTQ5ZGMtYjBlZi02YjllYWFmZWRlYjEvNWVjMTQ0NDgtMmU5ZC00MTRlLWJkZGItYzVhNzZkZDZiZDcyIiwiaWF0IjoxNzE2NTU3ODY1LCJleHAiOjMzMjg3MTE3ODY1fQ.OaewLmsFM1q6JrgSds0_JQTPIjJGhgVfmZ5KBISqjMk)

**Comment by samuelstroschein** [comment]
Is your repo public/can you share the link?

**Comment by NiklasBuchfink** [comment]
@goksugkdd Thank you for reporting the bug.

1. Is it possible to share a link to the repository or is it private?
2. Are you trying to push to the `main` branch of your repo and it is protected?

**Comment by NiklasBuchfink** [comment]
@goksugkdd Before everything else, can you check if the inlang GitHub app has access to your repository?

Here is how you can check this:
1. Go to your repository page on github.com
2. Click on Settings
3. Click on GitHub Apps -> Configure inlang
4. Set "Repository access" to "All repositories" or add your repo to the "Only select repositories" 
5. Click Save

**Comment by NiklasBuchfink** [comment]
@goksugkdd Lately, we had issues with our app permission flow for organizations.

1. If **you are the owner** of the repo, please check if Inlang GitHub is installed and has permission to access your repo.
2. If **you are not the owner** of the repo, request that the owner install the inlang GitHub app with sufficient permissions for the repo.
3. Also, make sure that your repo allows you to commit to the selected branch (e.g. some repos have direct commit to main disabled)

We are working on an update of the permission flow in this PR: https://github.com/opral/monorepo/pull/2905
I will close this issue in favor of: https://github.com/opral/inlang-fink/issues/36

Thanks for the issue and let me know if anything else comes up :)
