### ISSUE TITLE
Not able to push translations

### ISSUE THREAD

**Issue by Sukhvinder1106** [opral/inlang-fink#25]
I have completed my project and I am not able to push translations

**Comment by samuelstroschein** [comment]
Can you record a video or show screenshots?

**Comment by NiklasBuchfink** [comment]
Hey @Sukhvinder1106 👋 

Can you check if the inlang GitHub app has access to your repository?

Here is how you can check this:
1. Go to your repository page on github.com
2. Click on Settings
3. Click on GitHub Apps -> Configure inlang
4. Set "Repository access" to "All repositories" or add your repo to the "Only select repositories" 
5. Click Save

**Comment by NiklasBuchfink** [comment]
@Sukhvinder1106 Lately, we had issues with our app permission flow for organizations.

1. If **you are the owner** of the repo, please check if Inlang GitHub is installed and has permission to access your repo.
2. If **you are not the owner** of the repo, request that the owner install the inlang GitHub app with sufficient permissions for the repo.
3. Also, make sure that your repo allows you to commit to the selected branch (e.g. some repos have direct commit to main disabled)

We are working on an update of the permission flow in this PR: https://github.com/opral/monorepo/pull/2905
I will close this issue in favor of: https://github.com/opral/inlang-fink/issues/36

Thanks for the issue and let me know if anything else comes up :)
