### ISSUE TITLE
Show displayNames of language in Fink

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/inlang-fink#26]
### Context

We should show the normal human-readable language names in the Fink language dropdown

### Proposal

Use the `[Intl.DisplayNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames#language_display_names)` to show the English DisplayName with the BCP-47 tag behind. e.g.

* German `de`
* American English `en-US`
* Traditional Chinese `zh-Hant`

Open question: Should we keep the sorting

1. based on languageTags and maybe have the displayName in brackets or 
2. based on the displayNames

**Comment by NilsJacobsen** [comment]
Could also be nice tooltip for the message bundle component
