### ISSUE TITLE
Fink doesn't show me the other branches

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-fink#27]
<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/38183715-cd68-4dcb-9a51-d12bf2717fa6/6ee13670-afe6-4206-9090-c829889ecf0a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8zODE4MzcxNS1jZDY4LTRkY2ItOWE1MS1kMTJiZjI3MTdmYTYvNmVlMTM2NzAtYWZlNi00MjA2LTkwOTAtYzgyOTg4OWVjZjBhIiwiaWF0IjoxNzE2OTg1OTI1LCJleHAiOjMzMjg3NTQ1OTI1fQ.DM6hTzI015-0GnnUzHOB_QKVfjxyXQEqf8XvFo4WzjE " alt="image.png" width="609" height="230" />

Any idea why this happens?<br>When I click on main then on the next load I get them.

**Comment by NiklasBuchfink** [comment]
This is definitely because of the lazy loading of branch name, but why does this only occur in with our own repo again?

**Comment by NiklasBuchfink** [comment]
It seems to be a timing issue. Some operations take longer with our monorepo. If you wait long enough before clicking on main and it loads the branches.<br><br>I will fix it 👍

**Comment by samuelstroschein** [comment]
@niklas.buchfink how can this be a timing issue? does the lix sdk have no reactivity yet?

**Comment by NiklasBuchfink** [comment]
We do lazy branch fetching when the user clicks on the dropdown, because it is a heavy computation. Maybe it conflicts with the lazy loading now. I'll look into it.<br><br>cc @jan.johannes

**Comment by samuelstroschein** [comment]
@jan.johannes fyi you can directly create an issue from a comment in linear by clicking on the … and thereby increase the visibility that the issue has been created 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/9b8e52e1-dacc-4c2f-b847-62c0681087fd/27401f24-a76a-4d08-906c-4f43f1d09e92?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC85YjhlNTJlMS1kYWNjLTRjMmYtYjg0Ny02MmMwNjgxMDg3ZmQvMjc0MDFmMjQtYTc2YS00ZDA4LTkwNmMtNGY0M2YxZDA5ZTkyIiwiaWF0IjoxNzE3MTcyMTI3LCJleHAiOjMzMjg3NzMyMTI3fQ.qxwdBc9GnnpyxPaq8xV_iWahl5S99uy208EJhHdSVkM " alt="CleanShot 2024-05-31 at 12.15.06@2x.png" width="1772" height="502" />

**Comment by samuelstroschein** [comment]
linking [LIX-78](https://linear.app/opral/issue/LIX-78/get-remote-refs-sometimes-just-returns-the-main-branch-that-was)
