### ISSUE TITLE
searchable projects

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-fink#29]
### Context

It's hard to find the project "website" without a searchbox.

![CleanShot 2024-06-03 at 07.00.47@2x.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/f27464ab-f25c-4a44-958a-c91ed08ddff5/64de2c22-9466-4573-9106-5c30d3d545bd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9mMjc0NjRhYi1mMjVjLTRhNDQtOTU4YS1jOTFlZDA4ZGRmZjUvNjRkZTJjMjItOTQ2Ni00NTczLTkxMDYtNWMzMGQzZDU0NWJkIiwiaWF0IjoxNzE3NDE1MDA0LCJleHAiOjMzMjg3OTc1MDA0fQ.Yv0yBooaUEab0YwBlWU3e9F48L1KdmYg3A-uQmTejRA "=1556x")

### Proposal

Have a searchbar for the projects

![CleanShot 2024-06-03 at 07.02.12@2x.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/2ae14442-13d5-4004-b200-fe80177275f4/13b8263a-d086-4e83-ae4f-af5978970848?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8yYWUxNDQ0Mi0xM2Q1LTQwMDQtYjIwMC1mZTgwMTc3Mjc1ZjQvMTNiODI2M2EtZDA4Ni00ZTgzLWFlNGYtYWY1OTc4OTcwODQ4IiwiaWF0IjoxNzE3NDE1MDA0LCJleHAiOjMzMjg3OTc1MDA0fQ.YHS_EQYZ74aAMdaVC8magFl3yVOEMOxUyFqcaAb6tjQ "=794x")

**Comment by NiklasBuchfink** [comment]
This is a good improvement, but it's not that urgent as we are probably the only users with this problem.
