### ISSUE TITLE
save last selected project

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-fink#31]
### Context

[INWEB-96](https://linear.app/opral/issue/INWEB-96/move-inlang-project-from-root-to-website-folder) leads to an unsatisfying open fink experience for [https://fink.inlang.com/github.com/opral/monorepo](https://fink.inlang.com/github.com/opral/monorepo): 

The mock project `inlang-nextjs/project.inlang` is opened instead of the project i always want to edit `website.inlang`. 

### Proposal

Save the project selection of the user in localstorage to re-open the last opened project when opening a repository.

**Comment by NilsJacobsen** [comment]
I thought the same +1
