### ISSUE TITLE
Failed to push changes

### ISSUE THREAD

**Issue by oropezah** [opral/inlang-fink#34]
Failed to push changes
Please try again or file a bug. Failed to push

I have all my translation finished but this message keeps on appearing

**Comment by NiklasBuchfink** [comment]
@oropezah You probably need to update the permissions of the inlang GitHub app in GitHub. You can do it directly via GitHub and it should work.

We know this issue and it's a missing popup that directs you to the GitHub settings. I will do the last fix today that it is showing up again. Sorry for the inconvenience and please let me know if this helps.

**Comment by NiklasBuchfink** [comment]
Lately, we had issues with our app permission flow for organizations.

1. If **you are the owner** of the repo, please check if Inlang GitHub is installed and has permission to access your repo.
2. If **you are not the owner** of the repo, request that the owner install the inlang GitHub app with sufficient permissions for the repo.
3. Also, make sure that your repo allows you to commit to the selected branch (e.g. some repos have direct commit to main disabled)

We are working on an update of the permission flow in this PR: https://github.com/opral/monorepo/pull/2905
I will close this issue in favor of: https://github.com/opral/inlang-fink/issues/36

Thanks for the issue and let me know if anything else comes up :)
