### ISSUE TITLE
forking errors with 404

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-fink#35]
@samuel.stroschein said in [FINK-15](https://linear.app/opral/issue/FINK-15/growth-is-beginning-to-slow-down#comment-a2093bed):

> also not on [https://fink.inlang.com/github.com/StanGirard/quivr](https://fink.inlang.com/github.com/StanGirard/quivr). forking also failed
>
> <img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/f4742425-9774-4950-94e2-d74edca9a2a5/427cd84a-f29c-43a9-9cee-e63259d8aec2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9mNDc0MjQyNS05Nzc0LTQ5NTAtOTRlMi1kNzRlZGNhOWEyYTUvNDI3Y2Q4NGEtZjI5Yy00M2E5LTljZWUtZTYzMjU5ZDhhZWMyIiwiaWF0IjoxNzE3Njc2MjY5LCJleHAiOjMzMjg4MjM2MjY5fQ.hVcsgpt9pwruHMJtU34yTASMFTW3r2hSmTgITc96uyc " alt="CleanShot 2024-06-06 at 08.15.50@2x.png" width="2600" height="1166" />
>
> <img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/693e95b2-ff74-42dc-8406-7343b88afaf9/9c6ab719-fb97-440f-a03f-0167ccfb2c6a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC82OTNlOTViMi1mZjc0LTQyZGMtODQwNi03MzQzYjg4YWZhZjkvOWM2YWI3MTktZmI5Ny00NDBmLWEwM2YtMDE2N2NjZmIyYzZhIiwiaWF0IjoxNzE3Njc2MjY5LCJleHAiOjMzMjg4MjM2MjY5fQ.6Twn3A7F-m_RZ_KH_YBJtcgw1L3zJxy702JXytmWGP0 " alt="CleanShot 2024-06-06 at 08.16.01@2x.png" width="1202" height="594" />

**Comment by NiklasBuchfink** [comment]
cc @jan.johannes <br>I am not able to fork this repo, but forking [https://fink.inlang.com/github.com/remnoteio/translation](https://fink.inlang.com/github.com/remnoteio/translation) or [https://fink.inlang.com/github.com/osmosis-labs/osmosis-frontend](https://fink.inlang.com/github.com/osmosis-labs/osmosis-frontend) works fine.
