### ISSUE TITLE
decide on tech stack

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-fink#41]
### Context

We need to re-open the tech stack decision. Lit for SPAs is not a good match.

* Shadow DOM style encapsulation collides with how SPAs are developed, especially with Tailwind CSS. The result is a constant flash of styles when navigating pages.
* Lit has no state management solution suited for SPAs. Using \[context\])[https://www.npmjs.com/package/@lit/context](https://www.npmjs.com/package/@lit/context)) has no ergonomic way of setting state from childs. Every state change must come from the parent. 
* Vike had client side routing hickups where a fresh request to the server was executed. Don't know why. Not worth investigating further.  

### Options

**Framework**

1. Stick with lit for fink and continue trying to make it work. 
2. Use SolidJS as we did for fink v1
3. Use React. 

**Routing**

1. Vike even though we don't need SSR stuff. Just routing. 
2. If React is chosen, we can use production proven react router.

**Comment by samuelstroschein** [comment]
Gut feeling tells me to go with React 19. 

* finally support for web components 
* ecosystem (state management, routing, etc)
* at no risk of going unmaintained like Solid and Vike

@niklas.buchfink what choice would you make? 

[Web Components vs. React: Making the Switch](https://www.loom.com/share/0d74261dde344b7f94522c2a37bc34b1?sid=076db640-c570-4c48-9d80-38161d651250)

**Comment by samuelstroschein** [comment]
has potential impact on our websites too. ideally we have on tech stack choice cc @nils.jacobsen. <br><br>PS web components for individual components = great but the lack of app support = bad

**Comment by NilsJacobsen** [comment]
Wasn't there a concern about rendering with react. We choose solid because it performs better with the big lists?

**Comment by NilsJacobsen** [comment]
Can we already use react 19? It's still in experimental right? Do we know when it gets GA?

**Comment by samuelstroschein** [comment]
@nils.jacobsen yeah but react is getting a compiler now too. aka it will be fast enough. react 19 is in RC, we can start using it IMO

**Comment by samuelstroschein** [comment]
**Decision**<br>[https://www.loom.com/share/471045efba654d068f5db8aff4333643](https://www.loom.com/share/471045efba654d068f5db8aff4333643?sid=914bb8f2-e89f-49d9-a4fe-5877c8f95137)

1. Use react for apps and website
2. Use react router for routing
3. Use lit for components that should be shared across apps

**Why**

* Lit is not ready for SPA apps. State management is missing and lack of global styles a bummer. 
* React 19 (in RC since 2 months) has full support for web components and [performance is not a concern anymore](https://github.com/orgs/opral/discussions/420) with the new inlang sdk v2
* React router will get all things from Vike like code-splitting, ssr, static prerendering with v7 via a vite plugin (like VIke) but is vetted and financed by Shopify
