### ISSUE TITLE
Error machine translating to Japanese using Fink

### ISSUE THREAD

**Issue by flurret** [opral/inlang-fink#42]
See attached picture, I get this every time I try. I tried French and it worked fine, perhaps just Japanese has problems?

![image](https://github.com/user-attachments/assets/3eaf11ed-c50b-4954-9dc4-c9159dd3fe38)

**Comment by NiklasBuchfink** [comment]
@flurret Please change `jp` to `ja`.

- `jp` might be the country code for Japan
- you need `ja` the [BCP-47 language tag](https://en.wikipedia.org/wiki/IETF_language_tag) for Japanese  

This will fix your issue

**Comment by flurret** [comment]
Thanks Niklas, that works (I feel silly now though)

Might I suggest adding this to the error message i.e. add (double check your language code is BCP-47) or equivalent?

**Comment by samuelstroschein** [comment]
Hey @flurret, i opened an issue for a bcp47 validation rule [https://github.com/opral/inlang-message-sdk/issues/131](https://github.com/opral/inlang-message-sdk/issues/131).
