### ISSUE TITLE
Changelog should not be from website

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-fink#5]
<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/9111683f-2b09-4c3d-b672-5a107bd68e6c/75fe8f7b-cb09-4d71-bf5f-9d3ad2a07d9b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC85MTExNjgzZi0yYjA5LTRjM2QtYjY3Mi01YTEwN2JkNjhlNmMvNzVmZThmN2ItY2IwOS00ZDcxLWJmNWYtOWQzYWQyYTA3ZDliIiwiaWF0IjoxNzEwOTI0NDI2LCJleHAiOjMzMjgxNDg0NDI2fQ.A9vd5BeqyiyT5ZFMgL7ODvR5DRKv0pRciuZRSl36ITs " alt="image.png" width="1486" height="960" />

We should clean up the old changelog file.

**Comment by NiklasBuchfink** [comment]
It still has no changeset release yet. We can clean it up.
