### ISSUE TITLE
add feature to create bundles and messages

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-fink#52]
### Proposal

Add buttons to create new bundles and messages.

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/33f61cff-5f65-4825-8e4f-e6d3427e334d/95314818-cc49-4cf6-9434-aaaf7322b59b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8zM2Y2MWNmZi01ZjY1LTQ4MjUtOGU0Zi1lNmQzNDI3ZTMzNGQvOTUzMTQ4MTgtY2M0OS00Y2Y2LTk0MzQtYWFhZjczMjJiNTliIiwiaWF0IjoxNzI1NTU4OTUwLCJleHAiOjMzMjk2MTE4OTUwfQ.rRtPGhDigbNLRew0E0NVcKQ2j3vFnK_tn-DPWiaWmf0 " alt="CleanShot 2024-09-05 at 13.54.04@2x.png" width="2596" height="782" />

### Context

We can't test change control inserts and deletes of entities without it. 

cc @martin.lysk1

**Comment by NilsJacobsen** [comment]
Same as [FINK-70](https://linear.app/opral/issue/FINK-70/add-feature-to-delete-bundles-messages-variants#comment-47630cbd)

**Comment by samuelstroschein** [comment]
@niklas.buchfink you could retrieve the created_at from the lix change that a bundle creation causes

**Comment by NiklasBuchfink** [comment]
True, I just thought about it while cleaning the kitchen 😅
