### ISSUE TITLE
Filter options

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/inlang-fink#54]
### Context

Before Fink had multiple filter options. Helps when working with a large chunk of translations.

### Proposal

- [X] filter by language
- [X] filter by missing translations
- [X] basic search

**Comment by samuelstroschein** [comment]
if you want missing translation filters, then building [MESDK-204](https://linear.app/opral/issue/MESDK-204/missingtranslations-query-utility) in the SDK would be good. @felix.haeberle told me yesterday that he is going th ebuild the query
